name: medita_bk
description:

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 3.3.0+170

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  algolia: any
  aligned_tooltip: 0.0.1
  audio_service: ^0.18.18
  audio_session: any
  audio_video_progress_bar: ^2.0.3
  auto_size_text: 3.0.0
  cached_network_image: 3.4.1
  carousel_slider: ^5.1.1
  cloud_firestore: ^6.1.1
  cloud_functions: ^6.0.5
  collection: 1.19.1
  confetti: ^0.8.0
  connectivity_plus: ^7.0.0
  dropdown_button2: 2.3.9
  easy_debounce: ^2.0.3
  equatable: 2.0.7
  expandable: 5.0.1
  file_picker: ^10.3.8
  file_saver: 0.2.14
  path: ^1.9.0
  crypto: ^3.0.6
  firebase_analytics: ^12.1.0
  firebase_auth: ^6.1.3
  firebase_core: ^4.3.0
  firebase_crashlytics: ^5.0.6
  firebase_messaging: ^16.1.0
  firebase_storage: ^13.0.5
  flutter_animate: ^4.5.2
  flutter_app_badger: ^1.5.0
  flutter_local_notifications: ^19.5.0
  flutter_slidable: ^4.0.3
  flutter_timezone: ^5.0.0
  flutter_widget_from_html_core: ^0.17.0
  font_awesome_flutter: ^10.12.0
  from_css_color: 2.0.0
  go_router: ^17.0.1
  google_fonts: ^6.3.3
  google_sign_in: ^7.2.0
  http: ^1.6.0
  image_picker: ^1.2.1
  in_app_review: ^2.0.11
  infinite_scroll_pagination: ^5.1.1
  intl: any
  introduction_screen: ^4.0.0
  json_path: ^0.9.0
  just_audio: any
  just_audio_background: any
  just_audio_cache: any
  lottie: ^3.3.2
  mime: ^2.0.0
  mime_type: ^1.0.1
  package_info_plus: ^9.0.0
  page_transition: ^2.2.1
  path_provider: any
  pdfx: any
  percent_indicator: ^4.2.5
  provider: ^6.1.5+1
  rxdart: ^0.28.0
  share_plus: ^12.0.1
  shared_preferences: ^2.5.4
  sign_in_with_apple: 7.0.1
  stream_transform: ^2.1.1
  syncfusion_flutter_calendar: any
  syncfusion_flutter_charts: any
  timeago: 3.7.1
  timezone: ^0.10.1
  url_launcher: any
  video_player: any
  webview_flutter: any
  webview_flutter_android: ^4.10.11
  webview_flutter_wkwebview: ^3.23.5
  webviewx_plus:
    git:
      url: https://github.com/FlutterFlow/webviewx_plus.git
      ref: 4f84ece5e06d52643c5d844f41880baf8440c584

dependency_overrides:
  uuid: ^4.5.2
  algolia:
    path: third_party/algolia

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.7
  image: ^4.7.2
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
  image_path: "assets/images/app_launcher_icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/rive_animations/
    - assets/pdfs/
    - assets/jsons/

  fonts:
    - family: NavigationBar
      fonts:
        - asset: assets/fonts/navigation_bar.ttf
